export const ADD_SEEK_PRODUCT = 'ADD_SEEK_PRODUCT';
export const REMOVE_SEEK_PRODUCT = 'REMOVE_SEEK_PRODUCT';
export const SET_SEEK_PRODUCTS = 'SET_SEEK_PRODUCTS';
export const FETCH_SEEK_PRODUCTS_FAILED = 'FETCH_SEEK_PRODUCTS_FAILED';

export const PURCHASE_INIT = 'PURCHASE_INIT';